const $ = (selector) => document.querySelector(selector);
const token = location.pathname.split('/').filter(Boolean).pop();
const base = `/api/otp-share/page/${encodeURIComponent(token)}`;
const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
const formatTime = (value) => value ? new Date(value).toLocaleString('zh-CN', { hour12: false }) : '-';
function toast(message) { const el = $('#toast'); el.textContent = message; el.classList.remove('hidden'); setTimeout(() => el.classList.add('hidden'), 4000); }
async function api(path) { const response = await fetch(path); const data = await response.json(); if (!response.ok) throw new Error(data.detail || `HTTP ${response.status}`); return data; }
function otp(data) { const target = $('#share-otp-result'); target.innerHTML = `<strong>${escapeHtml(data.code)}</strong><span>${escapeHtml(data.subject || '')}</span>`; target.classList.remove('hidden'); }
function renderList(emails) { const target = $('#share-mail-list'); target.innerHTML = emails.map((email) => `<button class="mail-item" data-id="${escapeHtml(email.id)}"><strong>${escapeHtml(email.subject)}</strong><span>${escapeHtml(email.sender)}</span><time>${escapeHtml(formatTime(email.received_at))}</time></button>`).join('') || '<p class="muted">没有邮件</p>'; target.querySelectorAll('button').forEach((button) => button.onclick = () => detail(button.dataset.id).catch((error) => toast(error.message))); }
async function detail(id) { const data = await api(`${base}/emails/${encodeURIComponent(id)}`); const email = data.email; const target = $('#share-mail-detail'); const attachments = (email.attachments || []).filter((item) => !item.inline).map((item) => `<a class="btn ghost sm" href="${base}/emails/${encodeURIComponent(id)}/attachments/${encodeURIComponent(item.id)}">下载 ${escapeHtml(item.filename)}</a>`).join(''); target.innerHTML = `<div class="mail-detail-head"><h2>${escapeHtml(email.subject)}</h2><p>${escapeHtml(email.sender)} · ${escapeHtml(formatTime(email.received_at))}</p><button class="btn primary sm" id="detail-otp">提取 OTP</button></div><div class="mail-body"></div>${attachments ? `<div class="attachments"><h3>附件</h3>${attachments}</div>` : ''}`; const body = target.querySelector('.mail-body'); if (email.body_html) { const frame = document.createElement('iframe'); frame.setAttribute('sandbox', ''); frame.srcdoc = email.body_html; body.appendChild(frame); } else body.innerHTML = `<pre>${escapeHtml(email.body_text || '(无正文)')}</pre>`; $('#detail-otp').onclick = () => api(`${base}/emails/${encodeURIComponent(id)}/otp`).then((data) => otp(data.otp)).catch((error) => toast(error.message)); }
$('#share-otp-btn').onclick = () => api(`${base}/latest`).then((data) => otp(data.otp)).catch((error) => toast(error.message));
$('#share-read-btn').onclick = () => api(`${base}/emails`).then((data) => renderList(data.emails)).catch((error) => toast(error.message));
api(`${base}/mailbox`).then((data) => { $('#share-mailbox').textContent = `${data.mailbox.full_address}${data.expires_at ? ` · 有效至 ${formatTime(data.expires_at)}` : ' · 永久有效'}`; }).catch((error) => { $('#share-mailbox').textContent = error.message; });
